package pers.lcf.rents.forum.model;

import java.util.ArrayList;

import java.util.List;

public class PostsReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public PostsReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdIsNull() {
            addCriterion("posts_info_id is null");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdIsNotNull() {
            addCriterion("posts_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdEqualTo(String value) {
            addCriterion("posts_info_id =", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdNotEqualTo(String value) {
            addCriterion("posts_info_id <>", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdGreaterThan(String value) {
            addCriterion("posts_info_id >", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("posts_info_id >=", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdLessThan(String value) {
            addCriterion("posts_info_id <", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdLessThanOrEqualTo(String value) {
            addCriterion("posts_info_id <=", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdLike(String value) {
            addCriterion("posts_info_id like", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdNotLike(String value) {
            addCriterion("posts_info_id not like", value, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdIn(List<String> values) {
            addCriterion("posts_info_id in", values, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdNotIn(List<String> values) {
            addCriterion("posts_info_id not in", values, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdBetween(String value1, String value2) {
            addCriterion("posts_info_id between", value1, value2, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andPostsInfoIdNotBetween(String value1, String value2) {
            addCriterion("posts_info_id not between", value1, value2, "postsInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdIsNull() {
            addCriterion("user_info_id is null");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdIsNotNull() {
            addCriterion("user_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdEqualTo(String value) {
            addCriterion("user_info_id =", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdNotEqualTo(String value) {
            addCriterion("user_info_id <>", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdGreaterThan(String value) {
            addCriterion("user_info_id >", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_info_id >=", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdLessThan(String value) {
            addCriterion("user_info_id <", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdLessThanOrEqualTo(String value) {
            addCriterion("user_info_id <=", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdLike(String value) {
            addCriterion("user_info_id like", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdNotLike(String value) {
            addCriterion("user_info_id not like", value, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdIn(List<String> values) {
            addCriterion("user_info_id in", values, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdNotIn(List<String> values) {
            addCriterion("user_info_id not in", values, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdBetween(String value1, String value2) {
            addCriterion("user_info_id between", value1, value2, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andUserInfoIdNotBetween(String value1, String value2) {
            addCriterion("user_info_id not between", value1, value2, "userInfoId");
            return (Criteria) this;
        }

        public Criteria andReportTitleIsNull() {
            addCriterion("report_title is null");
            return (Criteria) this;
        }

        public Criteria andReportTitleIsNotNull() {
            addCriterion("report_title is not null");
            return (Criteria) this;
        }

        public Criteria andReportTitleEqualTo(String value) {
            addCriterion("report_title =", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleNotEqualTo(String value) {
            addCriterion("report_title <>", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleGreaterThan(String value) {
            addCriterion("report_title >", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleGreaterThanOrEqualTo(String value) {
            addCriterion("report_title >=", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleLessThan(String value) {
            addCriterion("report_title <", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleLessThanOrEqualTo(String value) {
            addCriterion("report_title <=", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleLike(String value) {
            addCriterion("report_title like", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleNotLike(String value) {
            addCriterion("report_title not like", value, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleIn(List<String> values) {
            addCriterion("report_title in", values, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleNotIn(List<String> values) {
            addCriterion("report_title not in", values, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleBetween(String value1, String value2) {
            addCriterion("report_title between", value1, value2, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportTitleNotBetween(String value1, String value2) {
            addCriterion("report_title not between", value1, value2, "reportTitle");
            return (Criteria) this;
        }

        public Criteria andReportImg1IsNull() {
            addCriterion("report_img1 is null");
            return (Criteria) this;
        }

        public Criteria andReportImg1IsNotNull() {
            addCriterion("report_img1 is not null");
            return (Criteria) this;
        }

        public Criteria andReportImg1EqualTo(String value) {
            addCriterion("report_img1 =", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1NotEqualTo(String value) {
            addCriterion("report_img1 <>", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1GreaterThan(String value) {
            addCriterion("report_img1 >", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1GreaterThanOrEqualTo(String value) {
            addCriterion("report_img1 >=", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1LessThan(String value) {
            addCriterion("report_img1 <", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1LessThanOrEqualTo(String value) {
            addCriterion("report_img1 <=", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1Like(String value) {
            addCriterion("report_img1 like", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1NotLike(String value) {
            addCriterion("report_img1 not like", value, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1In(List<String> values) {
            addCriterion("report_img1 in", values, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1NotIn(List<String> values) {
            addCriterion("report_img1 not in", values, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1Between(String value1, String value2) {
            addCriterion("report_img1 between", value1, value2, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg1NotBetween(String value1, String value2) {
            addCriterion("report_img1 not between", value1, value2, "reportImg1");
            return (Criteria) this;
        }

        public Criteria andReportImg2IsNull() {
            addCriterion("report_img2 is null");
            return (Criteria) this;
        }

        public Criteria andReportImg2IsNotNull() {
            addCriterion("report_img2 is not null");
            return (Criteria) this;
        }

        public Criteria andReportImg2EqualTo(String value) {
            addCriterion("report_img2 =", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2NotEqualTo(String value) {
            addCriterion("report_img2 <>", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2GreaterThan(String value) {
            addCriterion("report_img2 >", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2GreaterThanOrEqualTo(String value) {
            addCriterion("report_img2 >=", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2LessThan(String value) {
            addCriterion("report_img2 <", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2LessThanOrEqualTo(String value) {
            addCriterion("report_img2 <=", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2Like(String value) {
            addCriterion("report_img2 like", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2NotLike(String value) {
            addCriterion("report_img2 not like", value, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2In(List<String> values) {
            addCriterion("report_img2 in", values, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2NotIn(List<String> values) {
            addCriterion("report_img2 not in", values, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2Between(String value1, String value2) {
            addCriterion("report_img2 between", value1, value2, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andReportImg2NotBetween(String value1, String value2) {
            addCriterion("report_img2 not between", value1, value2, "reportImg2");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(String value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(String value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(String value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(String value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(String value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<String> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<String> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(String value1, String value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(String value1, String value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(String value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(String value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(String value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(String value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(String value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<String> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<String> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(String value1, String value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(String value1, String value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andHasHandleIsNull() {
            addCriterion("has_handle is null");
            return (Criteria) this;
        }

        public Criteria andHasHandleIsNotNull() {
            addCriterion("has_handle is not null");
            return (Criteria) this;
        }

        public Criteria andHasHandleEqualTo(Boolean value) {
            addCriterion("has_handle =", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleNotEqualTo(Boolean value) {
            addCriterion("has_handle <>", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleGreaterThan(Boolean value) {
            addCriterion("has_handle >", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("has_handle >=", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleLessThan(Boolean value) {
            addCriterion("has_handle <", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleLessThanOrEqualTo(Boolean value) {
            addCriterion("has_handle <=", value, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleIn(List<Boolean> values) {
            addCriterion("has_handle in", values, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleNotIn(List<Boolean> values) {
            addCriterion("has_handle not in", values, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleBetween(Boolean value1, Boolean value2) {
            addCriterion("has_handle between", value1, value2, "hasHandle");
            return (Criteria) this;
        }

        public Criteria andHasHandleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("has_handle not between", value1, value2, "hasHandle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts_report
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 12 14:51:29 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}