package pers.lcf.rents.forum.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.forum.model.PostsInfo;
import pers.lcf.rents.forum.model.PostsInfoExample;

import java.util.List;

@Mapper
public interface PostsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    long countByExample(PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int deleteByExample(PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insert(PostsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insertSelective(PostsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsInfo> selectByExampleWithBLOBs(PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsInfo> selectByExample(PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostsInfo record, @Param("example") PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PostsInfo record, @Param("example") PostsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_info
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExample(@Param("record") PostsInfo record, @Param("example") PostsInfoExample example);
}