package pers.lcf.rents.forum.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.forum.model.PostsReport;
import pers.lcf.rents.forum.model.PostsReportExample;

import java.util.List;

@Mapper
public interface PostsReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    long countByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int deleteByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insert(PostsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insertSelective(PostsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsReport> selectByExampleWithBLOBs(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsReport> selectByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostsReport record, @Param("example") PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PostsReport record, @Param("example") PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExample(@Param("record") PostsReport record, @Param("example") PostsReportExample example);
}