package pers.lcf.rents.forum.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import pers.lcf.rents.adminbase.model.Report;
import pers.lcf.rents.adminbase.model.User;
import pers.lcf.rents.forum.model.PostsReport;
import pers.lcf.rents.forum.model.PostsReportExample;

@Mapper
public interface PostsReportMapper {
    List<List<?>> getPostsReportsByDTO(@Param("record") Report Report, @Param("start") Integer start, @Param("end") Integer end);
    long countByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int deleteByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int insert(PostsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int insertSelective(PostsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    List<PostsReport> selectByExampleWithBLOBs(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    List<PostsReport> selectByExample(PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostsReport record, @Param("example") PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PostsReport record, @Param("example") PostsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_report
     *
     * @mbg.generated Tue Nov 12 14:51:29 CST 2019
     */
    int updateByExample(@Param("record") PostsReport record, @Param("example") PostsReportExample example);
}