package pers.lcf.rents.forum.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.forum.model.PostsImg;
import pers.lcf.rents.forum.model.PostsImgExample;

import java.util.List;

@Mapper
public interface PostsImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    long countByExample(PostsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int deleteByExample(PostsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insert(@Param("record") List<PostsImg>  record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insertSelective(PostsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsImg> selectByExample(PostsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostsImg record, @Param("example") PostsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_img
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExample(@Param("record") PostsImg record, @Param("example") PostsImgExample example);
}