package pers.lcf.rents.forum.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.forum.model.PostsComment;
import pers.lcf.rents.forum.model.PostsCommentExample;

import java.util.List;

@Mapper
public interface PostsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    long countByExample(PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int deleteByExample(PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insert(PostsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int insertSelective(PostsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsComment> selectByExampleWithBLOBs(PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    List<PostsComment> selectByExample(PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostsComment record, @Param("example") PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PostsComment record, @Param("example") PostsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts_comment
     *
     * @mbg.generated Sat Oct 05 21:14:01 CST 2019
     */
    int updateByExample(@Param("record") PostsComment record, @Param("example") PostsCommentExample example);
}