package pers.lcf.rents.userbase.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.userbase.model.RentsOut;
import pers.lcf.rents.userbase.model.RentsOutExample;

import java.util.List;

@Mapper
public interface RentsOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    long countByExample(RentsOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    int deleteByExample(RentsOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    int insert(RentsOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    int insertSelective(RentsOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    List<RentsOut> selectByExample(RentsOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") RentsOut record, @Param("example") RentsOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rents_out
     *
     * @mbg.generated Tue Nov 26 01:43:59 CST 2019
     */
    int updateByExample(@Param("record") RentsOut record, @Param("example") RentsOutExample example);
}