package pers.lcf.rents.userbase.mapper;

import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.userbase.model.UserMatch;
import pers.lcf.rents.userbase.model.UserStyle;
import pers.lcf.rents.userbase.model.UserStyleExample;

import java.util.List;

public interface UserStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    long countByExample(UserStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    int deleteByExample(UserStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    int insert(UserStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    int insertSelective(UserStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    List<UserStyle> selectByExample(UserStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserStyle record, @Param("example") UserStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_style
     *
     * @mbg.generated Fri Oct 04 08:56:50 CST 2019
     */
    int updateByExample(@Param("record") UserStyle record, @Param("example") UserStyleExample example);

    /**
     * @Param: [example]
     * @Return: java.util.List<pers.lcf.rents.userbase.model.UserMatch>
     * @Author: lcf
     * @Date: 2019/10/4 18:21
     * 找匹配舍友
     */
    List<UserMatch> selectUserMatchByExample(UserStyleExample example);

}