package pers.lcf.rents.adminbase.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pers.lcf.rents.adminbase.model.UserRealName;
import pers.lcf.rents.adminbase.model.UserRealNameExample;

import java.util.List;

@Mapper
public interface UserRealNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    long countByExample(UserRealNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    int deleteByExample(UserRealNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    int insert(UserRealName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    int insertSelective(UserRealName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    List<UserRealName> selectByExample(UserRealNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRealName record, @Param("example") UserRealNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_real_name
     *
     * @mbg.generated Sun Dec 01 16:31:16 CST 2019
     */
    int updateByExample(@Param("record") UserRealName record, @Param("example") UserRealNameExample example);
}